<?php

namespace App\Http;

abstract class Parametros {

    const GRUPO_LEITOR = 7;

    const SITUACAOPOST_AGENDADO = 3;
    const SITUACAOPOST_AGUARDANDOREVISAO = 4;
    const SITUACAOPOST_EMANDAMENTO = 6;
    const SITUACAOPOST_EMREVISAO = 5;
    const SITUACAOPOST_INATIVO = 7;
    const SITUACAOPOST_PENDENTE = 2;
    const SITUACAOPOST_PUBLICADO = 1;
    const SITUACAOPOST_RASCUNHO = 8;

    const TIPOESTATISTICA_CURTIDA = 1;
    const TIPOESTATISTICA_FAVORITO = 4;

    const TIPOFORMATO_FORMATODATA = 1;
    const TIPOFORMATO_FORMATOHORA = 2;
    const TIPOFORMATO_FORMATODATAHORA = 3;

}